name: Trigger auto deployment for test-containerapp-bcaf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-containerapp-bcaf-AutoDeployTrigger-8e07e5e2-41e9-492e-ac75-20fa1743a4dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTCONTAINERAPPBCAF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTCONTAINERAPPBCAF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTCONTAINERAPPBCAF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.TESTCONTAINERAPPBCAF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTCONTAINERAPPBCAF_REGISTRY_PASSWORD }}
          containerAppName: test-containerapp-bcaf
          resourceGroup: training_ai_agent
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


